#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2014
# Bernhard Stegmaier <stegmaier@sw-systems.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= sam9l9260.o
obj-y	+= led.o
obj-$(CONFIG_HAS_DATAFLASH) += partition.o
